---
# Name your file secrets.yml

development:
  DB_FILENAME: db/local/dev.db
  GMAP_TOKEN: googlemap_api_key

test:
  DB_FILENAME: db/local/test.db
  GMAP_TOKEN: googlemap_api_key

production:
  GMAP_TOKEN: googlemap_api_key