---
# Name your file secrets.yml

development:
  API_HOST: http://localhost:9090
  APP_HOST: http://localhost:9000
  GMAP_TOKEN: <your google map token>
  SESSION_SECRET: <some secret>

app_test:
  API_HOST: http://localhost:9090
  APP_HOST: http://localhost:9000

test:
  API_HOST: http://localhost:9090
  APP_HOST: http://localhost:9000
  GMAP_TOKEN: <your google map token>
  SESSION_SECRET: <some secret>

production:
  # - assign DATABASE_URL in production
  API_HOST: http://url.to.api
  APP_HOST: http://url.to.app
  GMAP_TOKEN: <your google map token>
  SESSION_SECRET: <some secret>